### ISSUE TITLE
Q: Is TeamCity 10.x supported?

### ISSUE THREAD

**Issue by simoneb** [jonnyzzz/TeamCity.Node#108]
Wondering if it's been tested there and if the zip available on the build server compiles against that version,

**Comment by jonnyzzz** [comment]
I know at least one install where it works. TeamCity api is stable between
versions too. I suppose it will work.

**Comment by simoneb** [comment]
K thanks, will confirm soon :)

**Comment by jonnyzzz** [comment]
Looking forward :)

**Comment by simoneb** [comment]
@jonnyzzz works!
