### ISSUE TITLE
Run NPM & Gulp at a solution level

### ISSUE THREAD

**Issue by Texernie** [jonnyzzz/TeamCity.Node#109]
If a solution has more than 1 MVC6 project where NPM and Gulp are needed, a separate build step has to be created for each project. It would be nice to be able to give it a solution file or a parent directory, and have the addin recurse the projects/directories looking for the required files, and subsequently executing NPM or gulp on each file appropriately.

**Comment by dragon788** [comment]
@Texernie This might be more easily accomplished by either having a root level Gulp file that has triggers for the other solutions, or a simple bit of scripting in a PowerShell step to find all the .gulpfiles and `pushd` to each directory, run `npm install`, and then `gulp` and then `popd` and repeat.

**Comment by Texernie** [comment]
@dragon788 What you have proposed is a possible work around. It does have its drawbacks in that simply adding a project to a solution and checking it into svn will not be automatically picked up in either proposed solution.  I do have a couple main issues with it too.

First, a powershell script that finds and runs all of the npm and gulps would mean that the files checked into SVN are tightly bound to the continuous integration environment. It is my understanding that the files in SVN are supposed to be agnostic about the CI environment with the exception of the relative pathing  relative to a build file or such and visa versa. A powershell script would have to know where npm and gulp are installed in order to run.

My second issue with that solution is that the npm and gulp task runners have broken the pattern of many other task runners. The task runners for nunit testing, nuget pack, nuget publish, etc all take wildcards for their targets. Npm and gulp take a single file. All I was suggesting is that as MVC6 gets more popular, that the NPM and Gulp tasks be modified to be more flexible instead of the bare minimum.
