### ISSUE TITLE
TeamCity 9.1.2: node.js and node.npm not detected

### ISSUE THREAD

**Issue by dlamanaancile** [jonnyzzz/TeamCity.Node#110]
Greetings,

We've installed the plug-in and restarted the TeamCity Server.  Users can see the runner, but all of the build agents show that node.js and node.npm are not detected.  Did we miss something?

Thanks!

**Comment by jonnyzzz** [comment]
Please check you have installed nodejs on agents and you have it available
in PATH of build agent process

**Comment by dlamanaancile** [comment]
Here is the part of the PATH:
C:\Program Files\nodejs\;C:\Program Files\nodejs\node_modules\npm;C:\Program Files\nodejs\node_modules\npm\bin;C:\Program Files\nodejs\node_modules\npm\lib;C:\Program Files\nodejs\node_modules\npm\lib\install;

nodejs is installed to C:\Program Files\nodejs

**Comment by jonnyzzz** [comment]
Does it work if you'd call nodejs from commandline runner? It may turn out
agent has different PATH

**Comment by dlamanaancile** [comment]
The command line runner is working fine.  The developer is OK with just using the command line runner.  Thank you for your help!
