### ISSUE TITLE
NPM Version

### ISSUE THREAD

**Issue by ScottReed** [jonnyzzz/TeamCity.Node#111]
Hi, I've updated the version on NPM on the build server to 3.10.7 using the standard npm -g install npm command. Locally on our dev machine it's creating the flat node_module structure as 3+ is supposed to however on the build server the temp directory is creating folder in the pre 3 nested node_modules folder way. I've checked the paths in the system variables and it's pointing to the nodejs folder and it's definitely running this version globally.

Do you have any ideas?

**Comment by dragon788** [comment]
@ScottReed you may need to purge your node_modules and let a new build recreate the folder. I'm not positive but npm may for backwards compatibility simply use the existing structure without rewriting everything (which could take a looooong time depending on how many modules you have).
