### ISSUE TITLE
NPM Build fails with exit code 0

### ISSUE THREAD

**Issue by richardklose** [jonnyzzz/TeamCity.Node#113]
I have a nodejs project which builds sucessfull, but the build is marked as failed in teamcity, altough it finished with exit code 0. It fails on npm install and any other npm task.

My build steps are:
1. Node.js NVM Installer
   -> Install Node.js 6.7.0 (already tried with older versions, same result)
2. Node.js NPM
   -> Run targets: install (npm install)
or any other npm target, result is always the same:
```

Step 2/4: Install dependencies (Node.js NPM)
[Step 2/4] Executing npm via wrapping shell script
[07:47:36][Step 2/4] Starting: /Applications/buildAgent/temp/agentTmp/wrapper8863962244314427089.sh install
[07:47:36][Step 2/4] in directory: /Applications/buildAgent/work/bdb0d20cc652fbd9
[Step 2/4] npm install
... (log is okay, it installs everything fine) ...
[Step 2/4] Process exited with code 0
[07:48:11][Step 2/4] Step Install dependencies (Node.js NPM) failed
```

or:

```
Step 3/4: Compile (Node.js NPM) (38s)
[07:48:11][Step 3/4] Executing npm via wrapping shell script
[07:48:11][Step 3/4] Starting: /Applications/buildAgent/temp/agentTmp/wrapper6644514504523704032.sh run build-dev
[07:48:11][Step 3/4] in directory: /Applications/buildAgent/work/bdb0d20cc652fbd9
[07:48:11][Step 3/4] npm run build-dev
... (log is also okay) ...
[Step 3/4] Process exited with code 0
[07:48:50][Step 3/4] Step Compile (Node.js NPM) failed
```

Because of 
`[07:48:11][Step 2/4] Step Install dependencies (Node.js NPM) failed`
and
`[07:48:50][Step 3/4] Step Compile (Node.js NPM) failed`
the build is marked as failed

It doesn't matter on which agent this runs, tried it on 
- Agent: mac OS 10.12
- Agent: Ubuntu 16.04

Teamcity Server: Ubuntu 14.04
using Teamcity 10.0.1 and Node.js build runner 1.0.80

I already tried to use several combinations of failure conditions, the result is always the same.
All Tasks run sucessfull, the results are all fine, but the build is marked as failed in Teamcity.

**Comment by Juraji** [comment]
I have the exact same issue, code 0 by NPM does not mean a failed build, it means a successful one.

Love the work you guys have done <3

**Comment by jonnyzzz** [comment]
What plugin version is it?

**Comment by Juraji** [comment]
1.0.85, it's the one from the Jetbrains repository link.

**Comment by yifei0420** [comment]
1.0.80 for me. Same issue. 

[Step 1/2] Process exited with code 0
[13:51:47][Step 1/2] Step Npm Install (Node.js NPM) failed

**Comment by Juraji** [comment]
While this is being fixed I kind of made a workaround by setting the following:

1. Edit the build configuration and go to Failure conditions
2. Uncheck "the build process exit code is not zero"
3. Add a failure condition matching for "does not contain" "Process exited with code 0" with "exact text"
4. Add a nice failure message

[Screenshot of settings](http://puu.sh/rzWnb/c00de38bac.png)

**Comment by jonnyzzz** [comment]
Pushed the fix. Sorry for that. Please give it a try once build is ready

**Comment by Juraji** [comment]
That was the fasted fix ever! Keep up the awesomeness!

**Comment by richardklose** [comment]
Works like a charm!

**Comment by sergosound** [comment]
а

**Comment by krakenstar** [comment]
I'm currently experience this with build 2019.1.4;
`Process exited with code 0
Step NPM Install Packages (Node.js NPM) failed`

**Comment by ituradastra** [comment]
I have the same issue with TeamCity Professional 2019.2.2 (build 71923)
