### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by kmathmann** [jonnyzzz/TeamCity.Node#116]
Is it posible to support Yarn in a future release?

**Comment by jonnyzzz** [comment]
Could you please elaborate. How do we support it in NPM runner? Do we need an extra runner for that or just a checkbox? What is the right way to fetch Yarn to have it fetch the rest?

**Comment by kmathmann** [comment]
[Yarn](https://yarnpkg.com/) is a new alternative NPM Client. It can be installed over npm `npm install --global yarn ` or with the yarn installer from their website. 
For example yarn caches npm packages and is so much faster than the original NPM Client.
Yarn dont need any special files, it can be used simultaneously to the original NPM Client.

[short Article about Yarn](https://medium.com/@shuvohabib/from-npm-to-yarn-should-i-go-for-it-or-not-8d71480ed270)

I don't know how TeamCity Plugins work. But Yarn is not a part of npm so i think that it needs an own runner. 

Is that what you need to know?

**Comment by jonnyzzz** [comment]
Thanks

What is a common practice for yard. Do one expect it to be installed on
every agent?  Or will it ok to download it for every build?

**Comment by kmathmann** [comment]
The common practise is to install yarn gloabally like you did it with npm. I think "installed on every agent" is global. Install yarn on every agent should be the best solution.

**Comment by wassim-azirar** [comment]
Is there any news about the support of [yarn](https://yarnpkg.com/) in TeamCity ?

**Comment by jonnyzzz** [comment]
PR is very welcome too! I'll try to find some time to fix that, but no estimate for now

**Comment by replete** [comment]
I'm watching this repository for Yarn support - it's much faster than npm in benchmarks, better caching and eliminates 'bad installs' with it's deterministic algorithm.

**Comment by fkrauthan** [comment]
I started creating a pull request #120 to add yarn support to this plugin.
