### ISSUE TITLE
No zip generated on Angular Project

### ISSUE THREAD

**Issue by endl3ssx** [jonnyzzz/TeamCity.Node#119]
Hi,

I have TeamCity version 10.0.3. I installed this plugin, configured it accordingly, my last step in the build steps is `grunt build`, the build succeeds, but I cannot see any artifacts being generated. On windows or linux when I `grunt build` my project, a `dist` folder is created which I have to upload to the remote nginx server. Any ideas?

Edit: I can see the folder has been generated on the agent in `/opt/jetbrains/teamcity/buildAgent/work/31270a28d727e9c1/dist` but how do I access this path from TeamCity to upload the dist folder to my SSH-connected server?

**Comment by jonnyzzz** [comment]
For deployment to SSH you may probably need a dedicated build runner, 
please check https://confluence.jetbrains.com/display/TCD10/Deployers
