### ISSUE TITLE
NVM-installed node not being detected by Windows-based agent

### ISSUE THREAD

**Issue by maxpavlov** [jonnyzzz/TeamCity.Node#121]
Hi.

After installing node 6.9.4 via NVM for Windows, on a machine where our Windows-based build agent is running, we are starting to get "no compatible agents found" with node.js and node.js.npm missing. Although if we check Build Runners tab, we see the support for both. Here are the screen shots of the relevant info:

![image](https://cloud.githubusercontent.com/assets/669701/22251606/19914f00-e254-11e6-9a59-d8d5b44802c1.png)

![image](https://cloud.githubusercontent.com/assets/669701/22251608/1ce37598-e254-11e6-94c4-36f5eecb38a7.png)

I've restarted the agent and the machine since setting node via nvm. I've also update the plugin to version 1.0.87.

TeamCity server is on the same Windows machine as the agent, and the version of server is 10.0.0. 

Please assist.

**Comment by jonnyzzz** [comment]
Current NVM support is only limited to Linux. Due to TeamCity api
limitations we report the problem that badly

Are you aware of any NVM packages for Windows?

**Comment by maxpavlov** [comment]
@jonnyzzz, I am using https://github.com/coreybutler/nvm-windows and it works pretty well other than the fact that recently TeamCity started to give the above-mentioned errors.

If I just go to the machine and open cmd.exe, both node and npm are in PATH, thus, work well. I don't know why TeamCity thinks agent is incompatible.

**Comment by jonnyzzz** [comment]
Would you like to help us contributing a pull request providing support of
NVM for Windows?

**Comment by maxpavlov** [comment]
I'm not a Java dev, although I think we just need to troublshoot the situation. Lets leave out NVM as a product that delivers node and npm to the machine.

What can cause team city to report "Unmet requiremment: node.js exists? What condition determines if it exists? Thanks.

**Comment by jonnyzzz** [comment]
It is NVM exactly. Currently we use linux only NVM. Changing requirements
will not solve the actual problem

**Comment by maxpavlov** [comment]
Let me clarify. Error:

![image](https://cloud.githubusercontent.com/assets/669701/22292002/e98062a6-e311-11e6-908d-391a104e2dbf.png)

appears due to NVM not being detected on the system by plugin code on agent?

**Comment by rob19780114** [comment]
Running into exactly the same problem here. I'm not a kotlin developer so far, but as far this is readable you nailed out support for windows-based os'es here:

https://github.com/jonnyzzz/TeamCity.Node/blob/master/agent/src/com/jonnyzzz/teamcity/plugins/node/agent/NodeDetector.kt#L43

**Comment by maxpavlov** [comment]
@rob19780114 Great, thanks for investigating this.
@jonnyzzz Please let us know when you can review a commit by @rob19780114 and perhaps build a new version. Thanks.

**Comment by maxpavlov** [comment]
@rob19780114 did you by any chance build your fork of the plugin to test out the solution?

**Comment by jonnyzzz** [comment]
@rob19780114 @maxpavlov than you for the patch! Could you please adopt it to use current user's path. BTW. Have you tried the patched version of the plugin? Does it work?

**Comment by maxpavlov** [comment]
@jonnyzzz while @rob19780114 probably can adopt it to use current user's path, testing it out on our side is really cumbersome since setting up a build environment is a large effort. If you are interested in keeping the pluggin operational on as many platforms as possible, which I am sure as an author you are, you'll be so kind to build it for us. I can test as soon as I have a .zip distro. I will be fast to write back with the results.

**Comment by maxpavlov** [comment]
@rob19780114 so the line should probably be:

`isWindows` && !File("System.getenv("USERPROFILE")\\AppData\\Roaming\\nvm\\nvm.exe").isFile

**Comment by rob19780114** [comment]
@maxpavlov Thanks for your improvement, i'll update it within the next few hours.

**Comment by jonnyzzz** [comment]
Please make sure the code will not throw NPE or use quoted `null`. As far
as I remember there are better environment variables to avoid hardcoding
appdata\roaming paths

As far as I remember, the plugin downloads nvm for Linux to setup yhe
specified version. I cannot see how detector only fix will work. Please
consider running plugin in test environment to make sure it works

**Comment by maxpavlov** [comment]
@rob19780114 

Yes, @jonnyzzz is right, one could use 

`isWindows && !File("System.getenv("APPDATA")\\nvm\\nvm.exe").isFile -> {`

to simplify the access.

Please submit a pull request. I doubt anyone except the author can test it out since setting up the test environment is a hard task for a non-TC/Kotlin developer as it seems to include TC installation for testing, Kotlin IDE or something. I briefly looked at the "How to build" section on readme.

Given a pull request perhaps we have a chance it will be fixed sometimes in the future.

**Comment by maxpavlov** [comment]
Ok, so I've changed the line in the detector code to:

`        isWindows && !File(System.getenv("APPDATA") + "\\nvm\\nvm.exe").isFile -> {`

built the plugin locally, installed it on our team city to test and it still shows 

node.js.npm exists
node.js exists

so the problem must be something else other then nvm detection. I've evaluated my expression in Debug and the Path being sent as a parameter into `!File(` is the correct one. I don't know where else to look thus any hints would be greatly appreciated. I have a build environment setup on my local machine for fast testing, which is good.

**Comment by maxpavlov** [comment]
Added pull request:
https://github.com/jonnyzzz/TeamCity.Node/pull/126

This concludes this problem's discussion. Thanks everyone for help.

**Comment by dragon788** [comment]
@maxpavlov Does this support having nvm installed in any other directories?

**Comment by dragon788** [comment]
Upon further examination it appears this does not actually detect nvm.exe if it is in the PATH, it only looks for it under a user's APPDATA directory. This could probably be more useful if it can locate nvm anywhere in the user/system PATH because when installing via Chocolatey it gets put into a system-wide directory not a user specific directory.

**Comment by matttrawicki** [comment]
I got the plugin detection to work on Windows by running TeamCity as a an Admin level user account and not System. But even if you get that far, you will hit the next roadblock -- the use of an ["eval" statement](https://github.com/jonnyzzz/TeamCity.Node/blob/1278ec191a48e0c78e731ab400e9f50b0a04d226/agent/src/com/jonnyzzz/teamcity/plugins/node/agent/nvm/NVM.kt#L112) in the command line command.

**Comment by jonnyzzz** [comment]
That looks like NVM issue. You may consider using other NVM version or fork
to avoid the `eval` problem

Best regards,
Eugene Petrenko

**Comment by alex3305** [comment]
@jonnyzzz No it doesn't. NVM should not be installed per user, but per environment. Since the script specifically checks for the user's `APPDATA` folder, it will generally fail when installing the package system wide.

Internally, we provided our own workaround with repackaging nvm for Windows with a modifiied installation directory.
