### ISSUE TITLE
Complete Windows Support

### ISSUE THREAD

**Issue by alex3305** [jonnyzzz/TeamCity.Node#133]
Although #126 added Windows support to this great plugin, the support is still not complete. The script step is still *nix only.

Both the Install and Use scripts that are provided by the NVMRunner, should implement Windows nvm commands or omit the Linux only commands. See: https://github.com/jonnyzzz/TeamCity.Node/blob/1278ec191a48e0c78e731ab400e9f50b0a04d226/agent/src/com/jonnyzzz/teamcity/plugins/node/agent/nvm/NVM.kt#L108-L112

Without eval, it seems that your plugin is running just fine, hopefully you can amend this or provide a workaround

**Comment by leewilson86** [comment]
I’ve supplied a fix for this issue. I’m just awaiting for @jonnyzzz to review my latest changes and hopefully the thumbs up to merge

**Comment by alex3305** [comment]
This seems solved in master. Thanks and closing.
