### ISSUE TITLE
Node.JS runner does not work with multiple arguments anymore

### ISSUE THREAD

**Issue by Mik13** [jonnyzzz/TeamCity.Node#138]
I upgraded the plugin from 1.0.55 to current stable.

Previously multiple line separated arguments worked like a charm. Now only one parameter is given to the script with all the lines in there (process.argv[2] is "test.json\nmorelines...").

My current workaround is switching to the command line runner, with node as executable, the script as first argument (first line) and with the additional arguments appended (from second line).

Is this an intended change?

![image](https://user-images.githubusercontent.com/1398427/31165677-3c0c4814-a8ec-11e7-88c5-64c36fb05b2b.png)

Thank you in advance.

**Comment by jonnyzzz** [comment]
It should work in the latest build
