### ISSUE TITLE
It is applied on TeamCity Testdriver?

### ISSUE THREAD

**Issue by betorobson** [jonnyzzz/TeamCity.Node#139]
Hi,

I'm getting really confused to make this plugin wok, I'm using a Testdrive project on Teamcity. 
I can not see the Node Build Step Runner. 

There is someone here that could help me with these doubts?

When I start with teamcity, I thought it would work in the same Heroku way like as Build Packs.

**Comment by jonnyzzz** [comment]
It's better to ask in TeamCity, sorry, this plugin not officially supported by the team.

https://confluence.jetbrains.com/display/TW/TeamCity+TestDrive
