### ISSUE TITLE
Not running webpack.config.js

### ISSUE THREAD

**Issue by buzzbonner** [jonnyzzz/TeamCity.Node#142]
Hi,

I'm using Webpack with Angular 4 and all is fine locally. However, I'm having problems with my CI process using this runner.

I've configured the runner with the following commands:

install
build:dist

build:dist is configured in package.json and successfully builds when running locally. However when running in TeamCity the build fails with log entry...

_No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.

Kind regards

Mark

**Comment by jonnyzzz** [comment]
I can be something with current working directory. Please check if you use
relative paths in the configuration

**Comment by buzzbonner** [comment]
Hi,

My root folder contains both my package.json and webpack.config.js.

*package.json:*

*"build:dist": "rimraf dist && webpack --env=prod"*

*webpack.config.js:*

*module.exports = function (env) {*
*    console.log(env);*
*    return require(`./config/webpack.${env}.js`);*
*}*

Kind regards

Mark

**Comment by buzzbonner** [comment]
Hi,

This problem is now fixed. An issue with source control.

Kind regards

Mark
