### ISSUE TITLE
Question about NVM

### ISSUE THREAD

**Issue by valeriob** [jonnyzzz/TeamCity.Node#145]
I need to run npm install on a project, so i made a build step Node.js NVM Installer to install node, and then a step Node.js NPM to restore packages.
Too bad all my build machines complaint about missing requirements : 
![image](https://user-images.githubusercontent.com/1522516/32718906-f0e1d358-c85e-11e7-925c-7b4297b8e6ed.png)

How can i use this to automate nvm installer so i can have a clean build machine.
Thanks

**Comment by jonnyzzz** [comment]
It assumes you have NVM available on the PATH of the build agent
process/user account. Due to a lack of TeamCity APIs, I implemented it via
a build start precondition. On start, it simply checks if `nvm` command
works​

**Comment by valeriob** [comment]
Thanks @jonnyzzz 
how do you suggest i archive my goal ?
I would like to have it working on a clean machine, if i add a step to install nvm will it work ?
Thanks

**Comment by jonnyzzz** [comment]
You need to install NVM manually on every agent machine

**Comment by valeriob** [comment]
Too bad nvm on windows is not friendly to teamcity and not maintained from nvm team, too bad..
At last i had to install node on machines, a shame...

**Comment by jonnyzzz** [comment]
Maybe it's worth to consider Docker or Linux for NVM/NPM

Best regards,
Eugene Petrenko
