### ISSUE TITLE
Unable to download Teamcity Node Plugin

### ISSUE THREAD

**Issue by nbonavia** [jonnyzzz/TeamCity.Node#146]
To whom it may concern,

I have tried to download the latest version of the plugin, but unfortunately the link https://teamcity.jetbrains.com/guestAuth/repository/download/bt434/.lastSuccessful/jonnyzzz.node.zip is not working and I was unable to download the latest version from Teamcity.

I tried to search for the latest successful build for Teamcity version 9.1.x (https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityNodePlugin_TeamCityNodeVs91x&branch_TeamCityNodePlugin=%3Cdefault%3E&tab=buildTypeStatusDiv), but could not find the download link to download the plugin zip file.

Can you please provide some help from where I can download the latest plugin version
Neville

**Comment by jonnyzzz** [comment]
You may try that one
https://teamcity.jetbrains.com/viewLog.html?buildId=878121&buildTypeId=bt434&tab=artifacts


Best regards,
Eugene Petrenko

**Comment by nbonavia** [comment]
It seems to be a very old version of the node plugin (1.0.85) where it does not have a 'working folder' option for Node.js NPM builds.

**Comment by nbonavia** [comment]
Thank you very much for that, however I have bumped into the issue identified by https://github.com/jonnyzzz/TeamCity.Node/issues/113

Do you have another version of the plugin that I can use and that has the issue resolved?

**Comment by ixax** [comment]
@jonnyzzz still 404 and last success build: `13 months ago`

**Comment by jonnyzzz** [comment]
There should be the fresh build now. Please have a look at
https://teamcity.jetbrains.com/project.html?projectId=TeamCityNodePlugin

Best regards,
Eugene Petrenko

**Comment by jonnyzzz** [comment]
It is fixed now. I have also pinned a fresh build to make sure it will not disappear
