### ISSUE TITLE
Unmet requirements node.js node.js npm

### ISSUE THREAD

**Issue by Tallies** [jonnyzzz/TeamCity.Node#157]
Hi, 

I added the teamcity-node-2.0.12 plugin to TeamCity 2018.1.2 (Azure RM Resource VM Template), and the agent (Cloud Agent: Windows OS docker container) seems to successfully get the plugin, and extract it, but get:

```
Unmet requirements:  
  node.js exists 
  node.js.npm exists
```

I saw https://github.com/jonnyzzz/TeamCity.Node/issues/152 and checked the contents of 2.0.12, verifying the fix discussed in that issue is in the zip I downloaded.

I don't get any exceptions (as per the previously mentioned bug) in my agent log, only that node, npm, yarn, grunt, bower and gulp 'was not found or failed'.

The full agent log:
[teamcity-agent.log](https://github.com/jonnyzzz/TeamCity.Node/files/2438465/teamcity-agent.log)

Kind regards,
Charl Marais

**Comment by Tallies** [comment]
My bad. Didn't realize I had to customize the default image and install node on the container.

Charl Marais

**Comment by tannerkozlowski** [comment]
My companies TeamCity. It's private. TeamCity version is 10.0.5.

I want to create packages from node.js app on TeamCity. So I added the teamcity-node-2.0.15 to TeamCity.

But, I faced the same issue. 
Unmet requirements:  
  node.js exists 
  node.js.npm exists

You said that "My bad. Didn't realize I had to customize the default image and install node on the container."
Would you explain it in more detail?
Thanks

**Comment by tannerkozlowski** [comment]
Server is Windows Server 2012 R2, version 6.3

**Comment by Tallies** [comment]
Sure. You had me worried there. I thought you meant you got and invite and admin rights on my TeamCity! :-p

The answer depends on your agents, or more specifically, where your agents are running. In my case, I'm running the TeamCity docker image on Azure as a Container Instance. The default TeamCity agent [jetbrains/teamcity](https://hub.docker.com/r/jetbrains/teamcity-agent/) image does not have Node installed, therefore the unmet requirements issue. 

You have to create a new image from the jetbrains one, and install node (or whatever other dependencies you have) on your version. You can either pull, modify the instance and create a new image from that, or pull and create a .DockerFile that install node on the container. 

If you're just using a agent on a VM of physical machine, you have to install node on the machine. 

Hope that helps,
Tals
