### ISSUE TITLE
Node.js NPM error

### ISSUE THREAD

**Issue by rlatn1234** [jonnyzzz/TeamCity.Node#184]
npm: command not found error occurs.

TeamCity Enterprise 2021.1 EAP1

**Comment by MetaMmodern** [comment]
@rlatn1234 hey buddy, how did you solve your problem?

**Comment by rlatn1234** [comment]
> @rlatn1234 hey buddy, how did you solve your problem?

I just installed node manually

**Comment by MetaMmodern** [comment]
> > @rlatn1234 hey buddy, how did you solve your problem?
> 
> I just installed node manually

Could you please share the command you used? I don't know what package manager is used by agent

**Comment by rlatn1234** [comment]
> > > @rlatn1234 hey buddy, how did you solve your problem?
> > 
> > 
> > I just installed node manually
> 
> Could you please share the command you used? I don't know what package manager is used by agent

i used docker image, so i installed with apt
installation step depends on agent OS
