### ISSUE TITLE
Builds fail if github is unreachable

### ISSUE THREAD

**Issue by calebTomlinson** [jonnyzzz/TeamCity.Node#48]
Our builds are failing when github goes down because it can't grab the nvm tarball.

If a build agent already has the plugin, an NVM version and the node version for a build, it should not fail.

**Comment by jonnyzzz** [comment]
The plugin downloads NVM binaries from GitHub repo by default. There is an option to specify another URL for download. You may simply host the binary in your local network and specify an explicit  value for the parameter ```NVM URL:```

This might be possible to use NPM repository to download NVM. Please file another issue if you think it's a nice to have feature for NVM downloader.

The other issue here is that the NVM script itself downloads node.js binaries from the internet. This means you scripts are also dependant on the health of the node.js web-site, not only on GitHub. I propose using patched NVM downloader script (locally hosted) that uses locally-hosted Node.js binaries.

**Comment by rob19780114** [comment]
@jonnyzzz Can you please add a clarification on the `NVM URL:` you mentioned`? I got no idea where to set this exactly.
