### ISSUE TITLE
Grunt Runner - Windows Error

### ISSUE THREAD

**Issue by mdridley** [jonnyzzz/TeamCity.Node#51]
Does not find grunt. Opened up that folder, ran command prompt "Grunt XXX" and it worked fine. Tried global install and local install through the NPM installer.

Stuck with this error:
Failed to find grunt.cmd under C:\BuildAgent\work\dfef5aa996caf151.
Please install grunt and grunt-cli as project-local Node.js NPM packages

Windows 2012, TeamCity Enterprise 8.1.2 (build 29993)

**Comment by YacheLee** [comment]
Does anyone solve this issue?
I have both install grunt from package.json and use the command of install grunt.
Both can't work. Please give me some hints,
I have tried whole day.
Thank you.

**Comment by zxspec** [comment]
add new build step of type "Node.js NPM"
into the npm commands add 2 commands:
_install grunt-cli
install_

**Comment by iwxfer** [comment]
I am quite new with TeamCity, Where can I add those commands? in my own project or TeamCity?

**Comment by zxspec** [comment]
![image](https://cloud.githubusercontent.com/assets/3115848/15153069/823a9204-16e0-11e6-9770-e015658641e0.png)
In your build configuration you have to find Build Steps tab
