### ISSUE TITLE
Node.js NVM Installer can use proxy?

### ISSUE THREAD

**Issue by robertmircea** [jonnyzzz/TeamCity.Node#61]
How can I setup Node.js NVM Installer to use either system proxy or recognize http_proxy or https_proxy environment variables?

**Comment by jonnyzzz** [comment]
You may use the following parameters in ```<agent>/conf/buildAgent.properties``` file:
```
teamcity.http.proxy.host.node
teamcity.http.proxy.port.node
teamcity.http.proxy.domain.node
teamcity.http.proxy.workstation.node
teamcity.http.proxy.user.node
teamcity.http.proxy.password.node
```
to specify proxy to be used for NVM.

You need to add this setting to **all** build agents that are affected.

The other workaround is to specify another URL (from local network) from which NVM is downloaded

**Comment by yamsellem** [comment]
I've added our proxy to one agent, and it's displayed in the Agent Parameters > Configuration Parameters. But I still get this error from NVM (every other build without NVM work).

```
[Step 1/4] Download: Fetching NVM
[Step 1/4] Failed to start build runner 'jonnyzzz.nvm'
[Step 1/4] java.net.UnknownHostException: github.com: unknown error
```

I' don't understand why this plugin is not using [the proxy flags](https://confluence.jetbrains.com/display/TCD9/How+To...#HowTo...-ConfigureTeamCitytoUseProxyServerforOutgoingConnections) provided on TeamCity launch.

**Comment by jonnyzzz** [comment]
It uses code from 
https://github.com/jonnyzzz/TeamCity.Node/blob/master/agent/src/com/jonnyzzz/teamcity/plugins/node/agent/nvm/HttpClient.kt
to fetch NVM.

Use `teamcity.http.proxy.host.node`, `teamcity.http.proxy.port.node` properties in `<agent>/conf/buildAgent.properties` file

**Comment by yamsellem** [comment]
Like I said, I have used those properties, but without success :-(.

**Comment by fjakop** [comment]
same issue here, we added
teamcity.http.proxy.host.node=http://proxy.my.company
teamcity.http.proxy.port.node=3128
but timeout every time downloading https://github.com/creationix/nvm/archive/v0.7.0.zip.

No problems setting https_proxy on bash and doing a wget to this url.

**Comment by brunorubin** [comment]
Same error here when trying to use with an agent behind a proxy.

I've tried to set ```teamcity.http.proxy.host.node``` and ```teamcity.http.proxy.port.node``` properties in ```<agent>/conf/buildAgent.properties``` file but no success.

As an alternative I've tried configure the JVM to use proxy, adding the JVM arguments as described on the [documentation](https://confluence.jetbrains.com/display/TCD9/How+To...#HowTo...-ConfigureTeamCitytoUseProxyServerforOutgoingConnections):
```
export JAVA_TEAMCITY_AGENT_OPTS="-Dproxyset=true
-Dhttp.proxyHost=proxy.domain.com
-Dhttp.proxyPort=8080
-Dhttp.nonProxyHosts=domain.com
-Dhttps.proxyHost=proxy.domain.com
-Dhttps.proxyPort=8080
-Dhttps.nonProxyHosts=domain.com"
```
Also I've tried to set it as an environment variable in the S.O, exporting the ```HTTP_PROXY``` and ```HTTPS_PROXY```.


Both three alternatives didn't work as expected. And got the same error and behavior in the agent when it tries to reach ```https://github.com```:
```
jetbrains.buildServer.agent.impl.buildStages.RunnerStageExecutionException: Failed to start build runner 'jonnyzzz.nvm'
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:27)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
...
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to https://github.com refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
...
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
```

As I could see, the properties  ```teamcity.http.proxy.host.node``` just sets a proxy for HTTP protocol, but it is trying to reach an URL using HTTPS protocol. I can be wrong but shouldn't be the case to use or specify a proxy handler to HTTPS protocol as well?

**Comment by rondoe** [comment]
other suggestion. download the zip and put it on one of your internal servers. under advanced options you can set the link to the package.
