### ISSUE TITLE
Change working directory

### ISSUE THREAD

**Issue by akuryan** [jonnyzzz/TeamCity.Node#63]
Is it possible to change working directory? 
In my git repositor package.json file is situated at folder 'Sources'
So, in order to do 'npm install', i should change working directory to Sources - but it is does not seems possible in plugin

**Comment by jonnyzzz** [comment]
You should find a ```Show advanced options``` in the build runner settings and click on it. It will expand additional parameters of the build runner. There you may specify the working directory for the build runner as relative path to the checkout directory (e.g. ```Sources``` for your case).
