### ISSUE TITLE
Run `npm install` from subfolder

### ISSUE THREAD

**Issue by skfd** [jonnyzzz/TeamCity.Node#67]
I have a Visual Studio solution with different projects. Each project has it's own `package.json`. It's a typical thing for Visual Studio projects.

I want an ability to do `cd myProject && npm install` or just specify path to folder where I want to run 'npm install'.

You [can not do it](https://github.com/npm/npm/issues/2974) using npm arguments.

Could there be a workaround for this?

**Comment by jonnyzzz** [comment]
You may click on `Show advanced options` link on the runner settings page. Than you should see `Working directory` field. All you need is to specify ```myProject``` there.
