### ISSUE TITLE
Update to support Team City 9.1

### ISSUE THREAD

**Issue by robertbaker** [jonnyzzz/TeamCity.Node#74]

**Comment by jonnyzzz** [comment]
Do you see any issues with 9.1?

**Comment by robertbaker** [comment]
I'm getting a ENOENT error with 9.1. Running the same npm/gulp commands in
the workfolder works fine, but not through TC. Not sure if it's your plugin
though. I'm using NPM 3.1.3 and Node 0.12.7

**Comment by jonnyzzz** [comment]
Please include agent, server and build logs

You should also check if you are able to run npm/gulp from a simple command
line runner to make sure node/npm/gukp is working
