### ISSUE TITLE
No plugin download available

### ISSUE THREAD

**Issue by Jandev** [jonnyzzz/TeamCity.Node#84]
It appears the plugin binaries can't be downloaded anymore from the specified link: http://teamcity.jetbrains.com/guestAuth/repository/download/bt434/.lastSuccessful/jonnyzzz.node.zip

Would be great to set up a working download link again.

I discovered the Teamcity site now (https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt434) and see there aren't any artifacts anymore besides from version 1.0.41. I've downloaded this old version now, still hope the new versions will become available again.

**Comment by olegomon** [comment]
Yes it is very hard to find a valid link.

**Comment by jonnyzzz** [comment]
Do you see how we can improve it?

Best regards,
Eugene Petrenko

**Comment by IainColledge** [comment]
Maybe link to the build page and say download the latest artifact?

**Comment by Jandev** [comment]
The link to the latest builds' artifacts is https://teamcity.jetbrains.com/viewLog.html?buildTypeId=bt434&buildId=lastSuccessful&tab=artifacts if I'm not mistaken.
You could link to this page.

There's of course a more advanced option, like publishing the artifacts to some build folder where users can download the latest (and previous) versions of the packages.
This could be extended with a script which updates page on github with the latest location.

The fastest solution would be to provide a link to the build page, like @IainColledge also mentions.

**Comment by 2tvenom** [comment]
Same problem.
Thank you

**Comment by jonnyzzz** [comment]
Thank you all for suggestions. Could someone probably provide a pull
request with update to the readme.md file?

**Comment by 2tvenom** [comment]
Sure, but i can't find available artifact here https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt434

Thank you

**Comment by IainColledge** [comment]
It's under the artifacts column and the last one you can access is from 2013.

**Comment by jonnyzzz** [comment]
I found the source of the issue. Please find the latest successful build
herre
https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt434

I'll fix compilation so the previous link would work

Best regards,
Eugene Petrenko

**Comment by jonnyzzz** [comment]
Updated. See #86

**Comment by IainColledge** [comment]
Thanks very much, appreciated.
