### ISSUE TITLE
Unable to download any plugin version later than 1.0.41

### ISSUE THREAD

**Issue by IainColledge** [jonnyzzz/TeamCity.Node#86]
If one goes to the builds page https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt434

The latest successful build with something to download in from 2013, version 1.0.41.

The latest version appears to be 1.0.69 but there is no way to download anything.

One impact is that there is no gulp runner available so would like to be able to download a version with gulp support please.

**Comment by gjoris** [comment]
+1

**Comment by SimonRupar** [comment]
+1

**Comment by jonnyzzz** [comment]
I made the plugin compile with latest Kotlin, fixed Kotlin downliad scripts, please find the fresh successful build on teamcity.jetbrains.com

**Comment by IainColledge** [comment]
Thanks very much, appreciated.
