### ISSUE TITLE
Setting NODE_ENV?

### ISSUE THREAD

**Issue by OndeVai** [jonnyzzz/TeamCity.Node#96]
Is there a way to set the NODE_ENV, especially for certain gulp tasks? We need this for our javascript builds.

Thanks!

**Comment by jonnyzzz** [comment]
You can set the environment variable on build parameters tab. Does it work
for you?

**Comment by OndeVai** [comment]
Sorry for my ignorance, but where would I find that build parameters tab?

**Comment by jonnyzzz** [comment]
https://confluence.jetbrains.com/display/TCD9/Configuring+Build+Parameters

Best regards,
Eugene Petrenko
