### ISSUE TITLE
Missing "manpath" tool when running TeamCity in Docker container based on java:8-jdk image

### ISSUE THREAD

**Issue by javierjeronimo** [jonnyzzz/TeamCity.Node#98]
Hello,

It seems that execution of "Node.js NVM Installer" results in running "manpath" tool, which is missing in our case:
```
[14:00:49][Install] /opt/TeamCity/buildAgent/system/jonnyzzz.nvm/nvm.sh: line 491: manpath: command not found
```

We are going to fix it by installing this required tool, but it will be useful to have a full list of requirements, or at least a recommended start point for the agent's environment. I mean, we started TeamCity inside a Docker container with an image based on java:8-jdk (https://github.com/docker-library/openjdk/blob/master/8-jdk/Dockerfile) so we are probably missing some other tools.

Regards.

**Comment by jonnyzzz** [comment]
We use nvm script. It looks like it requires some more packages. You may
check what packages are missing in you image. Why do you need NVM inside
docker? It may be way easier to create an image per node version instead

Best regards,
Eugene Petrenko

**Comment by javierjeronimo** [comment]
I added "Node.js NVM Installer" as first step without thinking it too much (I saw the recommendation somewhere in the docs). But, you are right, it makes no sense.

Anyway, it was a test. Now we have a remote agent and we use docker plugin to run all build steps inside a container (FROM node:4) so now it works, but without the use of this node.js plugin.

Thank you anyway.
